"""
image_content_writer.py — Claude-powered writer for portrait + carousel posts.

Public API:
    write_portrait(topic=None, outfit=..., recent_topics=...) -> dict
    write_carousel(topic=None, outfit=..., recent_topics=...) -> dict
    write_image_caption(content: dict) -> str
"""
from __future__ import annotations

import json
import logging
import os
import re
from typing import Optional

import httpx
from dotenv import load_dotenv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
load_dotenv(ROOT / ".env")
logger = logging.getLogger("virtuai.tools.image_content_writer")

KIE_CLAUDE_BASE = "https://api.kie.ai/claude/v1"
KIE_API_KEY = os.environ.get("KIE_API_KEY", "").strip()
MODEL = "claude-sonnet-4-6"


SYSTEM_PROMPT_BASE = """You write visual social-media content for an AI/automation business creator. Output is consumed by an automated image pipeline, so your output must be EXACT JSON.

LOCKED NICHE: AI + automation in real businesses. Operator-level voice (founder/builder who has shipped, NOT a guru). Every post must contain CONCRETE details: real dollar amounts, real tools (Claude, Zapier, Notion, Apollo, Cursor, Loom, etc.), specific timeframes, real roles.

LOCKED PERSONA IDENTITY (NON-NEGOTIABLE): the on-screen person is ALWAYS the same individual — Daniel Calder, a MAN in his early 30s, short dark hair, light stubble. EVERY image_prompt that shows the persona (uses_persona=true — the portrait and the carousel cover/recap slides) MUST describe HIM: literally begin that image_prompt with "a man in his early 30s". NEVER describe a woman, a different age, or a different person — even if the topic mentions a different role (e.g. "bookkeeper", "assistant", "VA", "nurse"). That role is what HE talks about, NOT who appears on camera. The person on camera is always the same man.

BANNED phrases (immediate rejection):
  • Generic AI-creator clichés: "unlock your potential", "in today's
    fast-paced world", "game changer", "embark on a journey",
    "elevate your", "supercharge", "revolutionize", "delve into",
    "next-level", "boost your", "skyrocket", "the power of",
    "navigate the", "groundbreaking", "transformative", "cutting edge",
    "best-in-class", "world-class".
  • Marketing buzz: leverage, synergy, hack your, 10x your, productivity
    tips, scale your business, future of work, harness the power,
    level up, disrupt the.
  • Tour-guide transitions: "let's dive in", "without further ado",
    "buckle up", "in conclusion", "to sum up".

VOICE — REAL-CREATOR, not AI-blog:
  • Write the way someone who already has the result would talk to a
    friend. Direct, contrarian, calm authority. Quotable. NEVER hyped.
  • Contractions ON ("you're", "I'd", "it's"). Short declaratives.
    One concrete noun beats five abstract adjectives.
  • First-person specifics. Name a real tool. Name a real number.
  • No exclamation marks. No emoji in body copy. No "guys".
  • If the line could've been auto-generated by 3 different AI tools,
    rewrite it.

CAPTION VOICE (post_caption_long):
  • Opens with a single short sentence — the hook.
  • Then 1-2 short paragraphs of context, with a real number and a
    real tool name inside.
  • Ends with a quotable aphorism — one line, save-able.
  • Reads conversational, not like a press release.

DESIGN HEURISTICS:
  • Headlines are SHORT and BIG: 1-5 words, often a number or imperative.
  • Subheads are 5-12 words. They reframe or pay off the headline.
  • A great slide can be read in 1.5 seconds. Compress brutally.
  • Visual prompts must produce photo-real, candid documentary imagery —
    NEVER stylized illustration, NEVER glowing-data-future-tech
    aesthetic. Real environments only.

SCENE-VARIETY DIMENSIONS (for every image_prompt in this post AND
across recent posts — diversify across these axes):
  • location           (cafe / park / desk / sidewalk / kitchen / studio / car / gym / hallway / rooftop / hotel lobby / workshop / library / patio)
  • camera angle       (eye-level / low / high / over-shoulder / handheld POV)
  • framing            (close-up / medium / wide / extreme wide)
  • lighting           (golden-hour / soft window / single practical / overcast diffuse / neon ambient / midday hard / blue-hour)
  • time of day        (morning / noon / golden hour / dusk / blue hour / night)
  • activity / posture (sitting / walking / standing / leaning / pacing / pouring coffee / typing / cooking)
  • props / objects    (notebook + pen / laptop / phone / espresso / cookbook / dumbbells / blueprint)
  • mood               (calm / urgent / contemplative / amused / determined)

OUTFIT-VARIETY DIMENSIONS (when describing what the speaker wears,
honor the `outfit` parameter passed to you AND vary across these
axes from recent posts):
  • type        (hoodie / tee / button-down / sweater / polo / henley / jacket / overshirt)
  • color       (navy / olive / charcoal / rust / cream / black / heather grey)
  • formality   (smart-casual / casual / dressed-up casual / weekend casual)
  • layer       (single layer / two-piece / jacket on top)
  • accessory   (watch / glasses / chain / cap / none)
  • season      (light cotton / heavier wool / mid-weight)
"""


def _headers():
    return {"Authorization": f"Bearer {KIE_API_KEY}", "Content-Type": "application/json"}


def _call_claude(system_msg: str, user_msg: str, max_tokens: int = 6000) -> str:
    resp = httpx.post(
        f"{KIE_CLAUDE_BASE}/messages",
        headers=_headers(),
        json={
            "model": MODEL,
            "max_tokens": max_tokens,
            "temperature": 0.85,
            "system": system_msg,
            "messages": [{"role": "user", "content": user_msg}],
        },
        timeout=120,
    )
    resp.raise_for_status()
    body = resp.json()
    content = body.get("content", [])
    text_parts = [c.get("text", "") for c in content if c.get("type") == "text"]
    return "\n".join(text_parts).strip()


def _strip_code_fence(s: str) -> str:
    s = s.strip()
    s = re.sub(r"^```(?:json)?\s*", "", s)
    s = re.sub(r"\s*```$", "", s)
    return s.strip()


# ── Portrait ────────────────────────────────────────────────────────────────

def _bullets(items: Optional[list[str]], limit: int = 8) -> str:
    if not items:
        return ""
    seen: list[str] = []
    for x in items[-limit:][::-1]:        # newest first, dedup
        if x and x not in seen:
            seen.append(x)
    return "\n".join(f"  ✗ {x}" for x in seen)


def _build_avoid_block(
    recent_topics:  Optional[list[str]],
    recent_outfits: Optional[list[str]],
    recent_moods:   Optional[list[str]],
    recent_scenes:  Optional[list[str]],
    recent_hooks:   Optional[list[str]],
) -> str:
    """Compile a 'do-not-repeat' brief for Claude from history dimensions."""
    sections: list[str] = []
    pairs = [
        ("topic patterns",          recent_topics),
        ("outfit descriptions",     recent_outfits),
        ("narrative moods",         recent_moods),
        ("scene locations / props", recent_scenes),
        ("opening hook patterns",   recent_hooks),
    ]
    for label, items in pairs:
        bulls = _bullets(items)
        if bulls:
            sections.append(f"\nRecently-used {label} — do NOT repeat:\n{bulls}")
    return "".join(sections)


PORTRAIT_SCHEMA = """
JSON schema for a single portrait post:
{
  "type": "portrait_quote",
  "topic": "string — 4-8 word title",
  "hook_summary": "string — the spoken hook line, ≤14 words",
  "headline": "string — the LARGE overlay text on the image, 2-6 words, all caps OK",
  "subhead": "string — smaller line beneath headline, 6-14 words",
  "image_prompt": "string — photo-real Nano Banana edit prompt placing the same MAN (Daniel, a man in his early 30s) in a specific real environment matching the message. Mention the outfit. Documentary candid style. No text in the image.",
  "post_caption_long": "string — the long Instagram/LinkedIn caption (200-500 words). Story-driven. Includes the headline as the opener. Ends with a quotable aphorism.",
  "hashtags": ["array", "of", "5-8", "lowercase", "hashtags"]
}
"""


def write_portrait(
    topic: Optional[str] = None,
    *,
    outfit: str = "dark polo shirt",
    recent_topics: Optional[list[str]] = None,
    mood: Optional[str] = None,
    recent_outfits: Optional[list[str]] = None,
    recent_moods: Optional[list[str]] = None,
    recent_scenes: Optional[list[str]] = None,
    recent_hooks: Optional[list[str]] = None,
) -> dict:
    """Generate a single portrait post: image prompt + headline + caption."""
    logger.info("Writing portrait post via Claude Sonnet 4.6...")
    avoid = _build_avoid_block(recent_topics, recent_outfits, recent_moods,
                                 recent_scenes, recent_hooks)
    topic_clause = f"Topic: {topic}\n" if topic else "Pick the topic yourself from the locked niche.\n"
    mood_clause = f"Mood: {mood}\n" if mood else ""

    user_msg = (
        f"Write ONE portrait quote post.\n\n"
        f"{topic_clause}{mood_clause}"
        f"Speaker outfit (must appear in image_prompt): {outfit}\n\n"
        + PORTRAIT_SCHEMA
        + avoid + "\n\nOutput ONLY the JSON object."
    )
    raw = _strip_code_fence(_call_claude(SYSTEM_PROMPT_BASE, user_msg))
    data = json.loads(raw)
    logger.info(f"  Portrait: '{data['headline']}' / '{data['subhead']}'")
    return data


# ── Carousel ────────────────────────────────────────────────────────────────

CAROUSEL_SCHEMA = """
JSON schema for a 5-slide carousel:
{
  "type": "carousel_5",
  "topic": "string — 4-8 word title",
  "hook_summary": "string — the cover slide hook, ≤12 words",
  "slides": [
    {
      "id": 1,
      "role": "cover",
      "headline": "string — 2-5 words, the scroll-stopping promise",
      "subhead": "string — 5-10 words, a small hint of what's inside",
      "image_prompt": "string — photo-real Nano Banana edit of the same MAN (Daniel, a man in his early 30s) looking directly at camera in a setting that matches the topic. Mention the outfit. Documentary candid.",
      "uses_persona": true
    },
    {
      "id": 2,
      "role": "problem",
      "headline": "string — typically a BIG NUMBER or short blunt phrase",
      "subhead": "string — names the painful reality, 6-14 words",
      "image_prompt": "string — abstract real-world scene (NO person), supports the problem. E.g., empty inbox, stack of invoices, blinking cursor, cluttered desk.",
      "uses_persona": false
    },
    {
      "id": 3,
      "role": "insight",
      "headline": "string — the contrarian reframe, 3-6 words",
      "subhead": "string — explains the reframe, 6-14 words",
      "image_prompt": "string — concrete real-world image of the contrarian thing (NO person), e.g., simple Zapier flow on a monitor, a whiteboard with one arrow, a phone showing a Notion page.",
      "uses_persona": false
    },
    {
      "id": 4,
      "role": "proof",
      "headline": "string — a specific number or outcome, 2-5 words",
      "subhead": "string — what specifically happened, 6-14 words with named tools",
      "image_prompt": "string — real-world image of the proof (NO person), e.g., dashboard showing rising graph, Stripe revenue page, calendar densely booked.",
      "uses_persona": false
    },
    {
      "id": 5,
      "role": "payoff",
      "headline": "string — the quotable aphorism, 5-9 words",
      "subhead": "string — a 4-6 word call to save the post",
      "image_prompt": "string — photo-real Nano Banana edit of the same MAN (Daniel, a man in his early 30s) in a different real environment from slide 1, looking thoughtful. Mention the outfit.",
      "uses_persona": true
    }
  ],
  "post_caption_long": "string — the IG/LinkedIn post caption that goes WITH the carousel. 200-500 words. Story form. Reuses the headlines as anchors.",
  "hashtags": ["array", "of", "5-8", "lowercase", "hashtags"]
}
"""


def write_carousel(
    topic: Optional[str] = None,
    *,
    outfit: str = "dark polo shirt",
    recent_topics: Optional[list[str]] = None,
    mood: Optional[str] = None,
    recent_outfits: Optional[list[str]] = None,
    recent_moods: Optional[list[str]] = None,
    recent_scenes: Optional[list[str]] = None,
    recent_hooks: Optional[list[str]] = None,
) -> dict:
    """Generate a 5-slide carousel post."""
    logger.info("Writing 5-slide carousel via Claude Sonnet 4.6...")
    avoid = _build_avoid_block(recent_topics, recent_outfits, recent_moods,
                                 recent_scenes, recent_hooks)
    topic_clause = f"Topic: {topic}\n" if topic else "Pick the topic yourself from the locked niche.\n"
    mood_clause = f"Mood: {mood}\n" if mood else ""

    user_msg = (
        f"Write ONE 5-slide carousel for Instagram + LinkedIn.\n\n"
        f"{topic_clause}{mood_clause}"
        f"Speaker outfit (must appear in slide 1 and 5 image prompts): {outfit}\n\n"
        + CAROUSEL_SCHEMA
        + avoid + "\n\n"
        "CRITICAL — the 5 slides MUST form a complete story arc:\n"
        "  1. COVER  (hook + promise)\n"
        "  2. PROBLEM (painful reality, often a number)\n"
        "  3. INSIGHT (the contrarian reframe — this is the meat)\n"
        "  4. PROOF  (specific outcome with tools/numbers named)\n"
        "  5. PAYOFF (quotable aphorism + 'save this')\n\n"
        "Slide 5 headline = the quote viewers will SAVE the carousel for. "
        "It must be tweetable on its own.\n\n"
        "Output ONLY the JSON object."
    )
    raw = _strip_code_fence(_call_claude(SYSTEM_PROMPT_BASE, user_msg, max_tokens=8000))
    data = json.loads(raw)
    logger.info(f"  Carousel: '{data['slides'][0]['headline']}' → '{data['slides'][-1]['headline']}'")
    return data


# ── Caption shortcut ────────────────────────────────────────────────────────

def write_image_caption(content: dict) -> dict:
    """Extract platform-specific captions from already-written content.

    Instagram and LinkedIn historically used the same 2000+ char essay-style
    long caption. LinkedIn tolerates that. Instagram does not — IG captions
    read better when they're tight: hook + 1-2 short paragraphs + closing
    aphorism + hashtags. So we build the IG variant from the first 1-2
    paragraphs of the long caption + the slide-5 / aphorism payoff line.

    LinkedIn keeps the long-form variant unchanged.
    """
    long_cap = content.get("post_caption_long", "") or ""
    hashtags = " ".join(f"#{h.lstrip('#')}" for h in content.get("hashtags", []))
    return {
        "instagram": _build_ig_caption(content, long_cap, hashtags),
        "linkedin":  (long_cap + "\n\n" + hashtags)[:3000],
        "tweet":     (content.get("hook_summary", "") + "\n\n" + hashtags)[:280],
        "alt_text":  content.get("hook_summary", "")[:180],
    }


def _build_ig_caption(content: dict, long_cap: str, hashtags: str,
                       target_body_chars: int = 380) -> str:
    """
    Build a punchy Instagram-style caption from already-written content.

    Shape:
        <opening paragraph(s) up to ~target_body_chars>

        <aphorism / slide-5 headline, if available>

        <hashtags>

    The total stays well under IG's 2200-char limit. We split the long
    caption on blank lines, take whole paragraphs only (no mid-sentence
    cuts), and stop once we'd exceed the soft body budget.
    """
    # 1. Pick the body — whole paragraphs of long_cap, in order, up to budget.
    paragraphs = [p.strip() for p in long_cap.split("\n\n") if p.strip()]
    # Skip horizontal-rule paragraphs ("---" alone)
    paragraphs = [p for p in paragraphs if p.strip("- ") != ""]

    body_parts: list[str] = []
    body_len = 0
    for p in paragraphs:
        if body_len and body_len + len(p) > target_body_chars:
            break
        body_parts.append(p)
        body_len += len(p) + 2  # account for the blank line separator
    body = "\n\n".join(body_parts).strip()

    # 2. Optional closing — slide-5 headline (the quotable payoff) if it
    #    isn't already inside the body we picked.
    closing = ""
    slides = content.get("slides") or []
    if slides and isinstance(slides, list) and isinstance(slides[-1], dict):
        s5 = (slides[-1].get("headline") or "").strip().strip('"').strip()
        if s5 and s5.lower() not in body.lower():
            closing = f'\n\n"{s5}"'

    # 3. Hashtags
    tag_block = f"\n\n{hashtags}" if hashtags else ""

    caption = (body + closing + tag_block).strip()
    return caption[:2200]   # IG hard cap, safety net


if __name__ == "__main__":
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    p = argparse.ArgumentParser()
    p.add_argument("mode", choices=["portrait", "carousel"])
    p.add_argument("--topic", default=None)
    p.add_argument("--outfit", default="navy zip-up hoodie")
    p.add_argument("--out", default=None)
    args = p.parse_args()

    fn = write_portrait if args.mode == "portrait" else write_carousel
    data = fn(topic=args.topic, outfit=args.outfit)
    out = args.out or f"virtuai/data/scripts/{args.mode}_{int(__import__('time').time())}.json"
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(json.dumps(data, indent=2))
    print(f"Wrote {out}")
    print(json.dumps(data, indent=2))
